// Writes src/version.ts from package.json. Runs as npm's `version` lifecycle
// script, so `npm version minor|patch` bumps both in the same commit; a test
// fails if the two ever drift. A constant (not a runtime read of
// package.json) so the Netlify bundle and the npm package agree.
import { readFileSync, writeFileSync } from "node:fs";
const { version } = JSON.parse(readFileSync(new URL("../package.json", import.meta.url), "utf8"));
writeFileSync(
  new URL("../src/version.ts", import.meta.url),
  `// GENERATED by scripts/sync-version.mjs from package.json — do not edit by hand.\nexport const VERSION = "${version}";\n`,
);
console.log(`src/version.ts ← ${version}`);
